# .circleci/config.yml

version: 2.1

#orbs:
#  macos: circleci/macos@2.2.0

jobs:
  build_and_test:
    macos:
      xcode: "13.1.0"
    steps:
      - checkout
      #- run:
        #  name: Install SwiftLint
        #  command: brew install swiftlint 
      - restore_cache:
          name: Restore CocoaPods
          keys:
            - pokedex-{{ checksum "Podfile.lock" }}-
            - pokedex- 
      - run: pod install
      - save_cache:
          name: Save CocoaPods
          key: pokedex-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      - run: xcodebuild build-for-testing -workspace "Pokedex.xcworkspace" -scheme "Pokedex" -destination "platform=iOS Simulator,name=iPhone 11"
      - run: xcodebuild test-without-building -workspace "Pokedex.xcworkspace" -scheme "Pokedex" -destination "platform=iOS Simulator,name=iPhone 11"
workflows: 
  build_and_test_workflow: 
    jobs: 
      - build_and_test

