# .circleci/config.yml

version: 2.1

jobs:
  build_and_test:
    macos:
      xcode: "14.3.1"
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run:
          name: Install SwiftLint
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint 
      - restore_cache:
          name: Restore CocoaPods
          keys:
            - pokedex-{{ checksum "Podfile.lock" }}-1
            - pokedex- 
      - run: pod install
      - save_cache:
          name: Save CocoaPods
          key: pokedex-{{ checksum "Podfile.lock" }}-1
          paths:
            - ./Pods
      - run: xcodebuild build-for-testing -workspace "Pokedex.xcworkspace" -scheme "Pokedex" -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4"
      - run: xcodebuild test-without-building -workspace "Pokedex.xcworkspace" -scheme "Pokedex" -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4"
workflows: 
  build_test_workflow: 
    jobs: 
      - build_and_test

